name: Analyzer

on: [push, pull_request]

jobs:
 analyzer:
  name: Bash Analysis
  runs-on: ubuntu-latest
  permissions:
   security-events: write
   contents: read
   actions: read
  steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Install ShellCheck
     run: sudo apt-get update && sudo apt-get install -y shellcheck
     
   - name: Run ShellCheck
     run: |
       find . -name '*.sh' -print0 | xargs -0 shellcheck
