name: Analyzer

on: [push, pull_request]

jobs:
 analyzer:
  name: Bash Analysis
  runs-on: ubuntu-latest
  permissions:
   security-events: write
   contents: read
   actions: read
  steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Run ShellCheck
     uses: ludeeus/action-shellcheck@v2
