name: Analyzer

on: [push, pull_request]

jobs:
 analyzer:
  name: Bash Analysis
  runs-on: ubuntu-latest
  permissions:
   security-events: write
   contents: read
   actions: read
  steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Install ShellCheck
     run: sudo apt-get update && sudo apt-get install -y shellcheck
     
   - name: Run ShellCheck
     id: shellcheck
     run: |
       OUTPUT=$(find . -name '*.sh' -print0 | xargs -0 shellcheck 2>&1) || true
       echo "$OUTPUT"
       echo "result<<EOF" >> $GITHUB_OUTPUT
       echo "$OUTPUT" >> $GITHUB_OUTPUT
       echo "EOF" >> $GITHUB_OUTPUT
       
   - name: Show ShellCheck
     run: echo "ShellCheck output: ${{ steps.shellcheck.outputs.result }}"
